[package]
name = "backyard-parser"
description = "Parse PHP code to AST node."
authors.workspace = true
edition.workspace = true
version.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
backyard-lexer = { workspace = true }
backyard-nodes = { workspace = true }