[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.package]
edition = "2021"
authors = ["Alzera Cita <alzeracita23@gmail.com>"]
version = "0.1.4"
repository = "https://github.com/Alzera/backyard"
license = "MIT"

[workspace.dependencies]
backyard-lexer = { path = "crates/backyard-lexer" }
backyard-nodes = { path = "crates/backyard-nodes" }
backyard-parser = { path = "crates/backyard-parser" }
backyard-generator = { path = "crates/backyard-generator" }
backyard = { path = "crates/backyard" }
backyard-test = { path = "crates/backyard-test" }

ts-rs = "10.0"
serde = { version = "1.0", features = ["derive"] }
serde-wasm-bindgen = "0.4"
wasm-bindgen = "0.2.95"
serde_json = "1.0"

[profile.release]
lto = true
strip = "symbols"
opt-level = "z"
codegen-units = 1