[package]
name = "backyard-lexer"
edition.workspace = true
version.workspace = true

[dependencies]
utils = { workspace = true }

ts-rs = { workspace = true }
serde = { workspace = true }
wasm-bindgen = { workspace = true }