[package]
name = "backyard-nodes"
description = "Nodes representing PHP code AST."
authors.workspace = true
edition.workspace = true
version.workspace = true
repository.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
ts-rs = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }